language: python
python:
  - '2.6'
  - '2.7'
install:
  - pip install -r requirements/test.txt --use-mirrors
  - python setup.py -q install
env: DJANGO_SETTINGS_MODULE=archer.settings DJANGO_CONFIGURATION=Test
script: nosetests

