language: python
python:
  - '2.6'
  - '2.7'
env:
  global:
    - DJANGO_SETTINGS_MODULE=uploader.settings
    - REUSE_DB=0
  matrix:
    - DJANGO_CONFIGURATION=ci_test
    - DJANGO_CONFIGURATION=ci_production DJANGO_CONFIG_FILE='./uploader/settings/ci.cfg'
install:
  - 'pip install -r requirements/${DJANGO_CONFIGURATION}.txt --use-mirrors'
  - pip install coveralls
script:
  - coverage run --source=uploader manage-cvmfs-stratum-uploader.py test
after_script:
  - python setup.py bdist

after_success:
  - coveralls


